name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]
env:
  SKIP_POSTINSTALL: 1

jobs:
  ci:
    uses: stevezhu/actions/.github/workflows/ci-node.yaml@v1
